baseURL = '/bit-list/'
title = "Bit List"
author = "Digital Preservation Coalition"
copyright = "Maintained by the <a class=\"text-muted\" href=\"https://dpconline.org/\">Digital Preservation Coalition</a>."

timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

theme = 'hugo-bootstrap-theme'
themesdir = 'node_modules/@filipecarneiro'

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

# 
mainSections = ['entries', 'posts']

# Add Markdown generation, which with the 'entries' Markdown template, generates the necessary pandoc input:
# (except this does not seem to be necessary, and causes problems for sections without a template)
#[outputs]
#  section = ['html', 'rss', 'markdown']


[frontmatter]
  date = ["date", "publishDate", "published", ":fileModTime", ":default"]
  lastmod = ["lastmod", "last-updated", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = 'authors'

# Doesn't seem to do much?
#disableKinds = ['taxonomy', 'term']


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons"
    target = "assets/bootstrap-icons"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font"
    target = "static/bootstrap-icons/font"

