baseURL = '/bit-list/'
title = "The Bit List"
author = "Digital Preservation Coalition"
copyright = "Maintained by the <a class=\"text-muted\" href=\"https://dpconline.org/\">Digital Preservation Coalition</a>."

timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

theme = 'hugo-bootstrap-theme'
themesdir = 'node_modules/@filipecarneiro'

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

# 
mainSections = ['species', 'posts']

[frontmatter]
  date = ["date", "publishDate", "lastmod", "last-updated" ]
  lastmod = ["lastmod", "last-updated", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  threat = 'threats'
  author = 'authors'

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons"
    target = "assets/bootstrap-icons"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/fonts"
    target = "static/bootstrap-icons/fonts"

#
# Add config to generate DecapCMS config etc. via Hugo
# https://discourse.gohugo.io/t/using-outputformats-to-generate-config-yml-in-a-certain-section/52308
#

[outputFormats]
  [outputFormats.AdminConfigYaml]
    baseName = 'config'
    isPlainText = true
    mediaType = 'application/yaml'

[mediaTypes]
  [mediaTypes.'application/yaml']
    suffixes = ['yml', 'yaml']