# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
longName = "The Global 'Bit List' of Endangered Digital Materials"
description = "The Bit List is a community-sourced list of at-risk digital content."
images = ['images/logo.svg','images/bit-list-logo.svg']
#mainMenuLogo = "images/logo-white.svg"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = true
alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = "Few Words About Us"
footerAboutText = "Footering Hither"

[options]
  bootStrapJs = true
  breadCrumb = true
  listCategoryFilter = false
  listTagFilter = false
