# config.yml
# ----------
# See here for documentation:
#   https://decapcms.org/docs/configuration-options/
#
#

# https://decapcms.org/docs/working-with-a-local-git-repository/
# If working locally, use the default proxy server port
local_backend: true

# A handy link back to the homepage:
site_url: "../"
logo_url: "../images/bit-list-logo.svg"

# How to talk to the Git datafile store:
backend:
  name: github
  repo: Digital-Preservation-Coalition/bit-list
  branch: main
  squash_merges: true
  # This enables contribution from non-repo-owners, but only works on GitHub:
  # https://decapcms.org/docs/open-authoring/
  open_authoring: false

# Where in the repository to store uploaded files (may be overridden for specific collection/fields below):
media_folder: "assets/uploads"

# Use the PR-based editorial workflow:
# https://decapcms.org/docs/editorial-workflows/
publish_mode: editorial_workflow

# Multi-language support
i18n:
  structure: multiple_files
  locales: [en]
  default_locale: en

# Defining the different collections of items:
collections:

- name: species
  label: Bit-List Species
  folder: content/species
  create: true
  path: '{{slug}}/index'
  media_folder: ''
  public_folder: ''
  i18n: true
  fields:
  - label: Title
    name: title
    widget: string
    required: true
    hint: "The full name of this species of digital preservation threat ??? this is a species under threat, not a threat????"
    i18n: true
  - label: Description
    name: description
    widget: text
    required: true
    hint: "A brief description of this species."
    i18n: true
  - label: Examples
    name: examples
    widget: string
    required: true
    hint: "Examples of this species."
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    hint: "??? This is a new field - is it a good idea to have to have an image for every entry?"
    i18n: duplicate
  - label: "Category"
    name: categories
    multiple: true
    required: false
    widget: relation
    collection: "categories"
    value_field: 'id'
    search_fields: ["title"]
    display_fields: ["title"]
    hint: "The category of digital species."
    i18n: duplicate
  - label: "Threats"
    name: threats
    multiple: true
    required: false
    widget: relation
    collection: "threats"
    value_field: 'id'
    search_fields: [ 'title' ] 
    display_fields: ['title']
    i18n: duplicate
  - label: "Tags"
    name: tags
    widget: "select"
    required: false
    multiple: true
    options:
      - "featured"
  - label: "Classification"
    name: classification
    multiple: false
    required: false
    widget: relation
    collection: "classifications"
    value_field: 'id'
    search_fields: [ 'title' ]
    i18n: duplicate
  - label: "Imminence of Action"
    name: imminence
    widget: "select"
    options:
      - { label: "(5) Act immediately within 6 months", value: 5 }
      - { label: "(4) Around 12 months", value: 4 }
      - { label: "(3) Less than 3 years", value: 3 }
      - { label: "(2) Within 5 years", value: 2 }
      - { label: "(1) More than 5 years", value: 1 }
    hint: "If you had one of these, how quickly would you need to act to save it?"
  - label: "Inevitability of Loss/Effort to Preserve"
    name: effort
    widget: "select"
    options:
      - { label: "(5) Inevitable", value: 5 }
      - { label: "(4) Loss seems likely", value: 4 }
      - { label: "(3) Major effort to fix", value: 3 }
      - { label: "(2) Small effort to fix", value: 2 }
      - { label: "(1) Entirely avoidable", value: 1 }
    hint: "Can it reasonably be avoided?"
  - label: Trends
    name: trends
    widget: list
    minimize_collapsed: false
    summary: '{{fields.year}} - {{fields.trend}} - {{fields.classification}}'
    fields:
    - { label: "Year", name: "year", widget: "number", value_type: "int" }
    - { label: "Trend", name: "trend", widget: "select", options: ['material-improvement', 'no-change', 'towards-greater-risk'] }
    - { label: "Classification", name: "classification", required: false, widget: "relation", collection: "classifications", value_field: "id", search_fields: ['title']}
    required: false
  - label: Hazards
    name: hazards
    widget: "text"
  - label: Mitigations
    name: mitigations
    widget: "text"
  - label: Case Studies & Examples
    name: case-studies
    i18n: false
    widget: list
    minimize_collapsed: false
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Author(s)", name: authors, widget: string, required: false }
    - { label: "Publisher", name: "publisher", widget: "string", required: false }
    - { label: "Year", name: year, widget: number, value_type: int, min: 1700, max: 2200, required: false }
    - { label: "URL", name: "url", widget: "string" }
    - { label: "Accessed At", name: "accessed", widget: "datetime", date_format: "YYYY-MM-DD", required: false }
    - { label: "Comment", name: "comment", widget: "markdown", buttons: ["bold", "italic", "link"], editor_components: [], required: false }
    required: false
    
# -------------
  - label: Year Added
    name: year-added
    widget: "number"
    value_type: "int"
    min: 2000
    max: 3000
    required: true
    i18n: duplicate
    hint: "The first year this entry was published."
  - label: "First Published"
    name: "published"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "??? Date this entry was first published - use full date rather than year above?"
    i18n: duplicate
    default: '{{now}}'
  - label: "Updated"
    name: "last-updated"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "Date this entry was last updated."
    i18n: duplicate
    default: '{{now}}'
  - label: Alias URLs
    name: aliases
    widget: list
    minimize_collapsed: true
    required: false
    hint: "Comma separated list of other URLs (for this site that should resolve to this item."
  - label: 'Discussion'
    name: 'body'
    widget: 'markdown'
    i18n: true
    hint: 'Discussion summarising the review process, outcome and history.'
  - label: 'Comments'
    name: 'comments'
    widget: 'markdown'
    i18n: true
    hint: 'Additional comments for this species.'

- name: classifications
  label: Classifications
  folder: content/classification
  create: false
  delete: false
  hide: false
  path: '{{slug}}'
  media_folder: '/assets/images/classification'
  public_folder: '/images/classification'
  i18n: true
  fields:
  - label: ID
    name: id
    widget: string
    required: true
    editable: false
    i18n: duplicate
    hint: "NOTE: Changing this ID will break all the links to this category."
  - label: Title
    name: title
    widget: string
    required: true
    i18n: true
  - label: Description
    name: description
    widget: string
    required: true
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    i18n: duplicate

- name: categories
  label: Categories
  folder: content/categories
  create: false
  delete: false
  hide: false
  path: '{{slug}}/_index'
  media_folder: '/assets/images/category'
  public_folder: '/images/category'
  i18n: true
  fields:
  - label: ID
    name: id
    widget: string
    required: true
    i18n: duplicate
    hint: "NOTE: Changing this ID will break all the links to this category."
  - label: Title
    name: title
    widget: string
    required: true
    i18n: true
  - label: Description
    name: description
    widget: string
    required: false
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    i18n: duplicate

- name: threats
  label: Threats
  folder: content/threats
  create: true
  delete: false
  hide: false
  path: '{{slug}}/_index'
  media_folder: '/assets/images/threats'
  public_folder: '/images/threats'
  i18n: true
  summary: '{{class}} > {{title}}'
  fields:
  - label: ID
    name: id
    widget: string
    required: true
    i18n: duplicate
    hint: "NOTE: Changing this ID will break all the links to this category."
  - label: Title
    name: title
    widget: string
    required: true
    i18n: true
  - label: Description
    name: description
    widget: string
    required: false
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    i18n: duplicate
  - label: "Threat Class"
    name: class
    widget: "select"
    options:
      - "Organisational Threats"
      - "Complexity Threats"
      - "Technological Threats"
    hint: "The broad class of threat this belongs to."

- name: pages
  label: 'Information Pages'
  folder: content
  create: false
  delete: false
  hide: false
  path: '{{slug}}'
  media_folder: '/assets/images/'
  public_folder: '/images/'
  i18n: true
  fields:
    - { label: 'Title', name: 'title', widget: 'string', default: 'Welcome' }
    - { label: 'Layout', name: 'layout', widget: 'select', options: ['single', 'single-toc', 'search'], required: false, i18n: duplicate }
    - { label: 'Body', name: 'body', widget: 'markdown' }


- name: local-groups
  label: Local Groups
  label_singular: Local Group
  folder: content/groups/local
  create: true
  delete: false
  hide: false
  path: '{{slug}}/index'
  media_folder: ''
  public_folder: ''
  i18n: false
  summary: '{{title}}'
  fields:
  - label: Title
    name: title
    widget: string
    required: true
    hint: "The name of the group, nice and short and stable."
  - label: "URL of homepage or primary contact"
    name: homepage_url
    widget: string
    required: false
    hint: "Link to a public web page that describes the group."
  - label: "URL of mailing list or forum"
    name: forum_url
    widget: string
    required: false
    hint: "Link to a web page that provides access to the associated mailing list or forum."
  - label: "Email Address To Contact"
    name: email
    widget: string
    required: false
    hint: "A contact email address. __WARNING! This will be made public along with the rest of the information on this page!__"
  - label: "Geographic Location"
    name: "location"
    widget: "map"
    hint: "Please indicate the rough centre of the region covered. Required for local groups."
    required: true
  - label: "Geographic Region"
    name: region
    widget: string
    required: true
    hint: "Please describe the overall geographic region this group covers."
  - label: 'Coverage'
    name: 'coverage'
    widget: 'image'
    required: false
    hint: "If you have an image that indicated the geographic coverage of this group, please add it here."
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    hint: "If this group has a logo, please add it here."
  - label: Further Details
    name: body
    widget: markdown
    required: false
    hint: "Any more to information you need to add?"

- name: organisations
  label: Organisations
  label_singular: Organisation
  folder: content/organisations
  create: true
  delete: false
  hide: false
  path: '{{slug}}/index'
  media_folder: '.'
  public_folder: '.'
  fields:
  - label: Title
    name: title
    widget: string
    required: true
  - label: URL
    name: homepage
    widget: string
    required: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
  - label: Owner/Contact
    name: contact
    widget: string
    required: false
    hint: "The individual who can be contacted about this workflow."

- name: workflows
  label: Workflows
  label_singular: Workflow
  folder: content/workflows
  create: true
  delete: false
  hide: false
  path: '{{slug}}/index'
  media_folder: ''
  public_folder: ''
  i18n: false
  summary: '{{title}}'
  fields:
  - label: Title
    name: title
    widget: string
    required: true
    hint: "The name of the group, nice and short and stable."
  - name: id
    label: ID
    widget: id
    regenerate: false
    prefix: wf
    hint: "An automatically-generated unique identifier for this workflow."
  - name: 'json'
    label: 'JSON (TEST)'
    widget: 'create-select'
    url: 'https://jsonplaceholder.typicode.com/users'
    attribute: 'name'
    mode: 'json'
  - label: Description
    name: description
    widget: text
    required: false
  - label: "Webinar"
    name: "webinar"
    widget: "relation"
    collection: "workflow_webinars"
    search_fields: ["webinars.*.title"]
    display_fields: ["webinars.*.title"]
    value_field: "webinars.*.title"
  - label: 'Primary Image'
    name: 'image'
    widget: 'image'
    required: false
    hint: "If there is an image that summarises the workflow, please add it here."
  - label: "Status"
    name: status
    widget: "select"
    options:
      - { label: "Draft", value: draft }
      - { label: "Experimental", value: experimental }
      - { label: "Testing", value: testing }
      - { label: "Production", value: production }
      - { label: "Decommissioned", value: decommissioned }
    hint: "What stage of development is this workflow at right now?"
    required: false
  - label: Tools
    label_singular: Tool
    name: tools
    widget: list
    minimize_collapsed: false
    collapsed: false
    add_to_top: true
    summary: '{{name}}'
    fields: 
      - { name: name, label: Tool Name, widget: string }
      - { name: url, label: Tool Homepage URL, widget: string }
    allow_add: true
    required: false
    hint: "The main digital preservation tools used in your workflow. Any names or URLs that match COPTR entries will be linked."
  - label: Input
    name: input
    widget: string
    required: false
    hint: "A single sentence describing what data or content will provide an input to the workflow."
  - label: Output
    name: output
    widget: string
    required: false
    hint: "A single sentence describing the resulting data or content that the workflow creates as an output."
  - label: Organisation
    name: organisation
    widget: relation
    required: false
    collection: organisations
    search_fields: ['title']
    value_field: '{{slug}}'
    display_fields: ['title']
    hint: "The organisation this workflow belongs to. If there's no match, you'll need to create an Organisation record first."
  - label: "First Published On"
    name: "published"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "Date this workflow was first published."
    default: '{{now}}'
  - label: Purpose, Context and Content
    name: context
    widget: markdown
    required: false
    hint: "Describe what your workflow is for - i.e. what it is designed to achieve, what the organisational context of the workflow is, and what content it is designed to work with."
  - label: Evaluation/Review
    name: review
    widget: markdown
    required: false
    hint: "How effective was the workflow? Was it replaced with a better workflow? Did it work well with some content but not others? What is the current status of the workflow? Does it relate to another workflow already described on the wiki? Link, explain and elaborate."
  - label: Further Information
    name: body
    widget: markdown
    required: false
    hint: "Provide any further information or links to additional documentation here."


- name: workflow_webinars
  label: Workflow Webinar Series
  label_singular: Workflow Webinar Series
  folder: content/workflow-webinars
  create: true
  delete: false
  hide: false
  path: '{{slug}}/index'
  media_folder: '.'
  public_folder: '.'
  i18n: false
  summary: '{{title}} : {{start}} - {{end}}'
  fields:
  - {label: Title, name: title, widget: string, default: ""}
  - label: Description
    name: body
    widget: markdown
    required: true
    hint: "About this webinar series."
  - label: Link
    name: link
    widget: string
    required: false
    hint: "A URL to any web page with further information."
  - label: "Start Date"
    name: "start"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "Date this series begins."
    picker_utc: true
  - label: "End Date"
    name: "end"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "Date this series begins."
    picker_utc: true
  - label: "Webinars"
    label_singular: Webinar
    name: webinars
    widget: "list"
    collapsed: false
    fields:
      - {label: Title, name: title, widget: string, default: ""}
      - label: "Starting At"
        name: "start"
        widget: "datetime"
        picker_utc: true
        hint: "The date and time this event starts (UTC)."
      - label: "Ending At"
        name: "end"
        widget: "datetime"
        picker_utc: true
        hint: "The date and time this event ends (UTC)."
      - label: Presentations
        label_singular: Presentation
        name: presentations
        widget: list
        collapsed: true
        fields:
        - {label: Title, name: title, widget: string, default: ""}
        - {label: Organisation, name: organisation, widget: string, default: ""}
        - {label: Presenter, name: presenter, widget: string, default: ""}
        - label: "Slides"
          name: "slides"
          widget: "file"
          required: false
          media_library:
            allow_multiple: false
            config:
              multiple: false
        - {label: Recording URL, name: recording_url, widget: string, required: false}
        - label: Workflows
          name: workflows
          widget: relation
          multiple: true
          required: false
          collection: workflows
          search_fields: ['title']
          value_field: '{{slug}}'
          display_fields: ['title']
      
