# config.yml
# ----------
# See here for documentation:
#   https://decapcms.org/docs/configuration-options/
#
#

# https://decapcms.org/docs/working-with-a-local-git-repository/
# If working locally, use the default proxy server port
local_backend: true

# A handy link back to the homepage:
site_url: /

# How to talk to the Git datafile store:
backend:
  name: github
  repo: Digital-Preservation-Coalition/bit-list
  branch: hugo
  squash_merges: true
  # This enables contribution from non-repo-owners, but only works on GitHub:
  # https://decapcms.org/docs/open-authoring/
  open_authoring: true

# Where in the repository to store uploaded files (may be overridden for specific collection/fields below):
media_folder: "assets/uploads"

# Use the PR-based editorial workflow:
# https://decapcms.org/docs/editorial-workflows/
publish_mode: editorial_workflow

# Path where the site is hosted:
# Not needed at present.
#site_url: /learning/

# Multi-language support
i18n:
  structure: multiple_files
  locales: [en]
  default_locale: en

# Defining the different collections of items:
collections:

- name: species
  label: Bit-List Species
  folder: content/species
  create: true
  path: '{{slug}}/index'
  media_folder: ''
  public_folder: ''
  i18n: true
  fields:
  - label: Title
    name: title
    widget: string
    required: true
    hint: "The full name of this species of digital preservation threat ??? this is a species under threat, not a threat????"
    i18n: true
  - label: Description
    name: description
    widget: text
    required: true
    hint: "A brief description of this species."
    i18n: true
  - label: Examples
    name: examples
    widget: string
    required: true
    hint: "Examples of this species."
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    hint: "??? This is a new field - is it a good idea to have to have an image for every entry?"
    i18n: duplicate
  - label: "Genus"
    name: categories
    multiple: true
    required: true
    widget: relation
    collection: "genus"
    value_field: "{{slug}}"
    search_fields: [ 'title' ]
    hint: "??? These classifications were called Digital Species before. Is Genus a better name? Or just use categories?"
    i18n: duplicate
  - label: 'Threat'
    name: 'threat'
    widget: 'select'
    options: ['social-media-cloud', 'hardware-obsolescence']
    required: true 
    i18n: duplicate
    hint: "??? This is the new threat classification, but not sure how to handle it yet."
  - label: "Status"
    name: status
    multiple: false
    required: true
    widget: relation
    collection: "statuses"
    value_field: "{{slug}}"
    search_fields: [ 'title' ] 
    i18n: duplicate
  - label: "Previous Status"
    name: previous-status
    multiple: false
    required: false
    widget: relation
    collection: "statuses"
    value_field: "{{slug}}"
    search_fields: [ 'title' ]
    i18n: duplicate
  - label: Decision
    name: decision
    widget: string
    required: true
    default: "consensus"
    i18n: duplicate
    hint: "??? What does this field mean? 'consensus' or?"
  - label: "Imminence of Action"
    name: imminence
    widget: "select"
    options:
      - { label: "(5) Act immediately within 6 months", value: 5 }
      - { label: "(4) Around 12 months", value: 4 }
      - { label: "(3) Less than 3 years", value: 3 }
      - { label: "(2) Within 5 years", value: 2 }
      - { label: "(1) More than 5 years", value: 1 }
    hint: "??? If you had one of these, how quickly would you need to act to save it?"
  - label: "Inevitability of Loss/Effort to Preserve"
    name: effort
    widget: "select"
    options:
      - { label: "(5) Inevitable", value: 5 }
      - { label: "(4) Loss seems likely", value: 4 }
      - { label: "(3) Major effort to fix", value: 3 }
      - { label: "(2) Small effort to fix", value: 2 }
      - { label: "(1) Entirely avoidable", value: 1 }
    hint: "??? Can it reasonably be avoided?"
  - label: "Impact"
    name: impact
    widget: "select"
    options:
      - { label: "(10) Globally traumatic, destabilizing impact to a large group of people", value: 10 }
      - { label: "(9) Internationally traumatic, destabilizing impact to a large group of people", value: 9 }
      - { label: "(8) Nationally traumatic, destabilizing impact to a large group of people", value: 8 }
      - { label: "(7) Locally traumatic, destabilizing impact to a large group of people", value: 7 }
      - { label: "(6) Impact to a large group of people", value: 6 }
      - { label: "(5) Impact to a smaller group of people", value: 5 }
      - { label: "(4) Inconvenient", value: 4 }
      - { label: "(3) Inconvenient, but quickly recoverable", value: 3 }
      - { label: "(2) Inconvenient to a smaller group of people, but quickly recoverable", value: 2 }
      - { label: "(1) Briefly inconvenient", value: 1 }
    hint: "??? What is the extent to which the loss of the digital material would be felt?"
  - label: "Significance"
    name: significance
    widget: "select"
    options:
      - { label: "(10) Unique, irreplaceable, invaluable, of global interest and importance to a large group of people", value: 10 }
      - { label: "(9) Unique, irreplaceable, invaluable, of international interest and importance to a large group of people", value: 9 }
      - { label: "(8) Unique, irreplaceable, invaluable, of national interest and importance to a large group of people", value: 8 }
      - { label: "(7) Unique, irreplaceable, invaluable, of community/local interest and importance to a large group of people", value: 7 }
      - { label: "(6) Irreplaceable, invaluable, of interest and importance to a large group of people", value: 6 }
      - { label: "(5) Invaluable and significant to a smaller group of people", value: 5 }
      - { label: "(4) Of some value and significance to a smaller group of people", value: 4 }
      - { label: "(3) Of some value or significance to a smaller group of people", value: 3 }
      - { label: "(2) Derivative and easily reproducible", value: 2 }
      - { label: "(1) Limited significance", value: 1 }
    hint: "??? What is the significance, value and/or 'uniqueness' of the digital material?"
  - label: Trends
    name: trends
    widget: list
    minimize_collapsed: false
    summary: '{{fields.year}} - {{fields.trend}}'
    fields:
    - { label: "Year", name: "year", widget: "number", value_type: "int" }
    - { label: "Trend", name: "trend", widget: "select", options: ['material-improvement', 'no-change', 'towards-greater-risk'] }
    required: false
  - label: Status in the Presence of Aggravating Conditions
    name: status-at-risk
    widget: "object"
    fields:
    - label: "Status"
      name: status
      multiple: false
      required: true
      widget: relation
      collection: "statuses"
      value_field: "{{slug}}"
      search_fields: [ 'title' ] 
      i18n: duplicate
    - label: Reasons
      name: reasons
      widget: "text"
  - label: Status in the Presence of Good Practice
    name: status-in-care
    widget: "object"
    fields:
    - label: "Status"
      name: status
      multiple: false
      required: true
      widget: relation
      collection: "statuses"
      value_field: "{{slug}}"
      search_fields: [ 'title' ] 
      i18n: duplicate
    - label: Reasons
      name: reasons
      widget: "text"


# -------------
  - label: Year Added
    name: year-added
    widget: "number"
    value_type: "int"
    min: 2000
    max: 3000
    required: true
    i18n: duplicate
    hint: "The first year this entry was published."
  - label: "First Published"
    name: "published"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "??? Date this entry was first published - use full date rather than year above?"
    i18n: duplicate
  - label: "Updated"
    name: "last-updated"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "Date this entry was last updated."
    i18n: duplicate
  - label: Alias URLs
    name: aliases
    widget: list
    minimize_collapsed: true
    fields:
    - { label: "Alias", name: "alias", widget: "string" }
    required: false
    hint: "Other URLs for this site that should resolve to this item."
  - label: 'Body'
    name: 'body'
    widget: 'markdown'
    i18n: true
    hint: '??? Currently, these sections are just free-text and loose headings - but this is perhaps a bad idea?'

- name: statuses
  label: Statuses
  folder: content/status
  create: false
  delete: false
  hide: false
  path: '{{slug}}'
  media_folder: '/assets/images/status'
  public_folder: '/images/status'
  i18n: true
  fields:
  - label: Title
    name: title
    widget: string
    required: true
    i18n: true
  - label: Description
    name: description
    widget: string
    required: true
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    i18n: duplicate

- name: genus
  label: Genus
  folder: content/genus
  create: false
  delete: false
  hide: false
  path: '{{slug}}'
  media_folder: '/assets/images/genus'
  public_folder: '/images/genus'
  i18n: true
  fields:
  - label: Title
    name: title
    widget: string
    required: true
    i18n: true
  - label: Description
    name: description
    widget: string
    required: false
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    i18n: duplicate

- name: pages
  label: 'Information Pages'
  folder: content
  create: false
  delete: false
  hide: false
  path: '{{slug}}'
  media_folder: '/assets/images/'
  public_folder: '/images/'
  i18n: true
  fields:
    - { label: 'Title', name: 'title', widget: 'string', default: 'Welcome' }
    - { label: 'Layout', name: 'layout', widget: 'select', options: ['single', 'single-toc', 'search'], required: false, i18n: duplicate }
    - { label: 'Body', name: 'body', widget: 'markdown' }
