# config.yml
# ----------
# See here for documentation:
#   https://decapcms.org/docs/configuration-options/
#
#

# https://decapcms.org/docs/working-with-a-local-git-repository/
# If working locally, use the default proxy server port
local_backend: true

# A handy link back to the homepage:
site_url: "../"
logo_url: "../images/bit-list-logo.svg"

# How to talk to the Git datafile store:
backend:
  name: github
  repo: Digital-Preservation-Coalition/bit-list
  branch: main
  squash_merges: true
  # This enables contribution from non-repo-owners, but only works on GitHub:
  # https://decapcms.org/docs/open-authoring/
  open_authoring: false

# Where in the repository to store uploaded files (may be overridden for specific collection/fields below):
media_folder: "assets/uploads"

# Use the PR-based editorial workflow:
# https://decapcms.org/docs/editorial-workflows/
# (combine with open authoring (above) for 'crowd sourcing')
#publish_mode: editorial_workflow

# Multi-language support
i18n:
  structure: multiple_files
  locales: [en]
  default_locale: en

# Defining the different collections of items:
collections:

- name: entries
  label: Bit-List Entries
  label_singular: Bit-List Entry
  folder: content/entries
  create: true
  path: '{{slug}}/index'
  media_folder: ''
  public_folder: ''
  i18n: true
  view_groups:
  - label: Classification
    field: classification
  - label: Imminence
    field: imminence
  - label: Effort
    field: effort
  fields:
  - name: id
    label: ID
    widget: id
    regenerate: false
    hint: "An automatically-generated unique identifier for this entry."
  - label: Title
    name: title
    widget: string
    required: true
    hint: "The full name of this kind of digital material."
    i18n: true
  - label: Description
    name: description
    widget: text
    required: true
    hint: "A brief description of this kind of digital material."
    i18n: true
  - label: Examples
    name: examples
    widget: string
    required: true
    hint: "Examples of this kind of digital material."
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    hint: "??? This is a new field - is it a good idea to have to have an image for every entry?"
    i18n: duplicate
  - label: "Category"
    name: categories
    multiple: true
    required: false
    widget: relation
    collection: "categories"
    value_field: 'title'
    search_fields: ["title"]
    display_fields: ["title"]
    hint: "The category of digital materials."
    i18n: duplicate
  - label: "Threats"
    name: threats
    multiple: true
    required: false
    widget: relation
    collection: "threats"
    value_field: 'title'
    search_fields: [ 'title' ] 
    display_fields: ["{{class}} > {{title}}"]
    i18n: duplicate
    hint: "Select the threats that apply to these materials. The first one will be the one this entry appears under in the printed version."
  - label: "Tags"
    name: tags
    widget: "select"
    required: false
    multiple: true
    options:
      - "featured"
  - label: "Classification"
    name: classification
    multiple: false
    required: false
    widget: relation
    collection: "classifications"
    value_field: 'id'
    search_fields: [ 'title' ]
    i18n: duplicate
  - label: "Imminence of Action"
    name: imminence
    widget: "select"
    options:
      - { label: "(5) Act immediately within 6 months", value: 5 }
      - { label: "(4) Around 12 months", value: 4 }
      - { label: "(3) Less than 3 years", value: 3 }
      - { label: "(2) Within 5 years", value: 2 }
      - { label: "(1) More than 5 years", value: 1 }
    hint: "If you had one of these, how quickly would you need to act to save it?"
  - label: "Inevitability of Loss/Effort to Preserve"
    name: effort
    widget: "select"
    options:
      - { label: "(5) Inevitable", value: 5 }
      - { label: "(4) Loss seems likely", value: 4 }
      - { label: "(3) Major effort to fix", value: 3 }
      - { label: "(2) Small effort to fix", value: 2 }
      - { label: "(1) Entirely avoidable", value: 1 }
    hint: "Can it reasonably be avoided?"
  - label: Trends
    name: trends
    widget: list
    minimize_collapsed: false
    summary: '{{fields.year}} - {{fields.trend}} - {{fields.classification}}'
    fields:
    - { label: "Year", name: "year", widget: "number", value_type: "int" }
    - { label: "Trend", name: "trend", widget: "select", options: ['material-improvement', 'no-change', 'towards-greater-risk'] }
    - { label: "Classification", name: "classification", required: false, widget: "relation", collection: "classifications", value_field: "id", search_fields: ['title']}
    required: false
  - label: Hazards
    name: hazards
    widget: "text"
  - label: Mitigations
    name: mitigations
    widget: "text"
  - label: Case Studies & Examples
    name: case-studies
    i18n: false
    widget: list
    minimize_collapsed: false
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Author(s)", name: authors, widget: string, required: false }
    - { label: "Publisher", name: "publisher", widget: "string", required: false }
    - { label: "Year", name: year, widget: number, value_type: int, min: 1700, max: 2200, required: false }
    - { label: "URL", name: "url", widget: "string", required: false }
    - { label: "Accessed At", name: "accessed", widget: "datetime", date_format: "YYYY-MM-DD", required: false }
    - { label: "Comment", name: "comment", widget: "markdown", buttons: ["bold", "italic", "link"], editor_components: [], required: false }
    required: false
  - label: "Related entries"
    name: related-entries
    multiple: true
    required: false
    widget: relation
    collection: "entries"
    value_field: "{{slug}}"
    search_fields: [ 'title' ] 
    display_fields: ['title']
    i18n: duplicate

# -------------
  - label: Year Added
    name: year-added
    widget: "number"
    value_type: "int"
    min: 2000
    max: 3000
    required: true
    i18n: duplicate
    hint: "The first year this entry was published."
  - label: "First Published"
    name: "published"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "??? Date this entry was first published - use full date rather than year above?"
    i18n: duplicate
    default: '{{now}}'
  - label: "Updated"
    name: "last-updated"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    hint: "Date this entry was last updated."
    i18n: duplicate
    default: '{{now}}'
  - label: Alias URLs
    name: aliases
    widget: list
    minimize_collapsed: true
    required: false
    hint: "Comma separated list of other URLs (for this site that should resolve to this item."
  - label: 'Discussion'
    name: 'body'
    widget: 'markdown'
    i18n: true
    hint: 'Discussion summarising the review process, outcome and history.'
  - label: 'Additional Information'
    name: 'comments'
    widget: 'markdown'
    required: false
    i18n: true
    hint: 'Additional information for this entry.'

- name: classifications
  label: Classifications
  folder: content/classification
  create: false
  delete: false
  hide: false
  path: '{{slug}}'
  media_folder: '/assets/images/classification'
  public_folder: '/images/classification'
  i18n: true
  fields:
  - name: id
    label: ID
    widget: id
    regenerate: false
    hint: "An automatically-generated unique identifier for this workflow."
  - label: Title
    name: title
    widget: string
    required: true
    i18n: true
  - label: Description
    name: description
    widget: string
    required: true
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    i18n: duplicate
  - label: Weight
    name: weight
    widget: "number"
    value_type: "int"
    min: 0
    max: 100
    required: true
    i18n: duplicate
    hint: "The 'weight' to give this item, higher numbers mean lower in lists."
  

- name: categories
  label: Categories
  folder: content/categories
  create: false
  delete: false
  hide: false
  path: '{{slug}}/_index'
  media_folder: '/assets/images/category'
  public_folder: '/images/category'
  i18n: true
  fields:
  - name: id
    label: ID
    widget: id
    regenerate: false
    hint: "An automatically-generated unique identifier for this workflow."
  - label: Title
    name: title
    widget: string
    required: true
    i18n: true
  - label: Description
    name: description
    widget: string
    required: false
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    i18n: duplicate

- name: threats
  label: Threats
  label_singular: Threat
  folder: content/threats
  create: true
  delete: true
  hide: false
  path: '{{slug}}/_index'
  media_folder: '/assets/images/threats'
  public_folder: '/images/threats'
  i18n: true
  view_groups:
  - label: Class
    field: class
  fields:
  - name: id
    label: ID
    widget: id
    regenerate: true
    hint: "An automatically-generated unique identifier for this workflow."
  - label: Title
    name: title
    widget: string
    required: true
    i18n: true
  - label: Description
    name: description
    widget: string
    required: false
    i18n: true
  - label: 'Image'
    name: 'image'
    widget: 'image'
    required: false
    i18n: duplicate
  - label: "Threat Class"
    name: class
    widget: "select"
    options:
      - "Organisational"
      - "Complexity"
      - "Content"
      - "Technological"
    hint: "The broad class of threat this belongs to."

- name: pages
  label: 'Information Pages'
  folder: content
  create: false
  delete: false
  hide: false
  path: '{{slug}}'
  media_folder: '/assets/images/'
  public_folder: '/images/'
  i18n: true
  fields:
    - { label: 'Title', name: 'title', widget: 'string', default: 'Welcome' }
    - { label: 'Layout', name: 'layout', widget: 'select', options: ['single', 'single-toc', 'search'], required: false, i18n: duplicate }
    - { label: 'Body', name: 'body', widget: 'markdown' }

