[[main]]
name = "Home"
pageRef = "/index"
weight = 10

[[main]]
name = "About"
pageRef = "/about"
weight = 20
title = "About the Bit List"

[[social]]
  name = "GitHub"
  pre = "<i class='bi bi-github'></i>"
  url = "https://github.com/Digital-Preservation-Coalition/bit-list/"
  weight = 10
  title = "Visit the GitHub project"
