[[main]]
name = "Home"
pageRef = "/index"
weight = 10

[[main]]
name = "About"
pageRef = "/about"
weight = 20
title = "About the Bit List"

[[main]]
name = "Search"
pageRef = "/search"
weight = 25
title = "Search"

[[main]]
identifier = "browse"
name = "Browse"
weight = 40

[[main]]
identifier = "entries"
name = "Entries"
pageRef = "/entries"
weight = 10
parent = "browse"

[[main]]
name = "Classifications"
pageRef = "/classification"
weight = 15
parent = "browse"

[[main]]
name = "Categories"
pageRef = "/categories"
weight = 20
parent = "browse"

[[main]]
name = "Threats"
pageRef = "/threats"
weight = 30
parent = "browse"

[[social]]
  name = "GitHub"
  pre = "<i class='bi bi-github'></i>"
  url = "https://github.com/Digital-Preservation-Coalition/bit-list/"
  weight = 10
  title = "Visit the GitHub project"
