[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "About"
url = "about"
weight = 20
title = "About the Bit List"

[[main]]
name = "Search"
url = "search"
weight = 25
title = "Search"

[[main]]
identifier = "browse"
name = "Browse"
weight = 40

[[main]]
identifier = "species"
name = "Species"
url = "species"
weight = 10
parent = "browse"

[[main]]
name = "All"
url = "post"
weight = 100
parent = "browse"

[[main]]
name = "Hugo"
url = "tags/hugo"
weight = 20
parent = "browse"

[[main]]
name = "Bootstrap"
url = "tags/bootstrap"
weight = 30
parent = "browse"

[[main]]
identifier = "docs"
name = "Docs"
url = "page"
weight = 50
parent = "browse"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/Digital-Preservation-Coalition/bit-list/"
  weight = 10
  title = "Visit the GitHub project"
